### ISSUE TITLE
Higher resolution support

### ISSUE THREAD

**Issue by markusbkk** [SCUMM-Next/SCUNK#3]
SCUMM version 6 can quite handily support a resolution of 640x480 or even higher.
The main culprit at the time seems to have been the absence of higher-end hardware, not a limitation of the actual software.

I've already tested converting the assets of [OpenQuest](https://github.com/SCUMM-Next/SCUNK/tree/master/examples/openquest) to 640x480 (obviously, this doesn't yield a pixel perfect result. But I digress).

With minimal code changes in the script (changing `setScreen(0, 200)` to `setScreen(0, 480)` and temporarily getting rid of `screenEffect` invokations — they work normally but are much too slow due to the VM not accounting for the higher resolution)
and one small change in either VM (forcing a 640x480 resolution in the included **scvm** debugging VM or in **ScummVM**), all is well.

**TODO**:

- [ ] Figure out how to support multiple resolutions
   - [ ] Potentially, this needs to be done through the build system and with two different IDs/versions. i e `SCUNK.000` and `SCUNKLOW.000` (`TARGET_VERSION` inside `example.mak` can be used for these purposes, once SCUMM Version 7 has been retired)
- [ ] Add screen effects for higher resolutions 
   - [ ] Potentially, this can be solved by adding a second parameter, `duration`, to `screenEffect`
- [ ] Add a high resolution example
- [ ] Prepare a PR for ScummVM

**Comment by markusbkk** [comment]
Note that some screen effects (such as `0x05` AKA "Box Opening" ) are directly affected by `VAR_FADE_DELAY`, whereas others (such as `0x87` AKA "Columns dissolve") seemingly the same speed no matter what.
